In [16]:
from collections import Counter
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import numpy as np
from scipy.spatial.distance import cdist

In [35]:
class knn(object):
    def __init__(self,k):
        self.k = k
    def train(self, x, y):
        self.X_train = x
        self.y_train = y
    def eu_dis(self, X_test):
        num_test = X_test.shape[0]
        num_train = self.X_train.shape[0]
        dis = cdist(X_test, self.X_train, 'minkowski')
        return dis
    def pred(self, dis):
        num_test = dis.shape[0]
        y_pred = np.zeros(num_test)
        for i in range(num_test):
            y_indices = np.argsort(dis[i,:])
            closest_y = self.y_train[y_indices[:self.k]]
            y_pred[i] = np.argmax(np.bincount(closest_y))
        return y_pred

In [36]:
iris = datasets.load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)
X_train, X_test, y_train, y_test = np.array(X_train), np.array(X_test), np.array(y_train), np.array(y_test)

In [37]:
classifier = knn(k=1)
classifier.train(X_train, y_train)
dist = classifier.eu_dis(X_test)
y_test_pred = classifier.pred(dist)

In [38]:
print(confusion_matrix(y_test, y_test_pred))

[[ 9  0  0]
 [ 0 13  0]
 [ 0  0  8]]
