In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from scipy.spatial.distance import cdist
from collections import Counter
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [2]:
class KNN:
    def __init__(self, k = 3):
        self._k = k
        self._neighbors = None
    def fit(self, X, y):
        self._X = X #data
        self._y = y #target
        return self
    def __predict(self, column):
        neighbors = tf.gather_nd(self._y, tf.reshape(column, (-1,1)))
        return Counter(neighbors.numpy()).most_common()[0][0]
    def predict(self, X):
        distances = cdist(self._X, X, 'euclidean')
        arg_sorted_distances = tf.argsort(distances, axis = 0)
        neighbors = arg_sorted_distances[:self._k]
        predictios = tf.map_fn(self.__predict, tf.transpose(neighbors))
        return tf.cast(predictios, 'float32')

In [12]:
iris = datasets.load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)

#print(iris)

k = 3
iris_knn = KNN(k=k)
iris_knn.fit(X_train, y_train)
predictions = iris_knn.predict(X_test)

print(confusion_matrix(y_test, predictions))

[[ 9  0  0]
 [ 0 13  0]
 [ 0  0  8]]
